blank_issues_enabled: false
contact_links:
  - name: Ferris-Lib Discord server
    url: https://discord.gg/Cxhmkb8rsg
    about: Please visit our Discord server for questions and support requests.
  -name: FerrisChat Discord Server
    url: https://discord.gg/sUF76B887J
    about: Please visit our Discord server for questions and support requests.  